modLoader="javafml"
loaderVersion="${loader_version_range}"
license="CC0-1.0"
issueTrackerURL="https://github.com/gnmyt/VoxelDash/issues"

[[mods]]
modId="voxeldash"
version="${mod_version}"
displayName="VoxelDash"
authors="GNM"
displayURL="https://voxeldash.dev/"
displayTest="IGNORE_ALL_VERSION"
description='''
A simple dashboard for your Minecraft server.
'''

[[dependencies.voxeldash]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="SERVER"

[[dependencies.voxeldash]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"
