name: CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  modules:
    name: Modules
    uses: ./.github/workflows/build-modules.yml

  dashboard:
    name: Dashboard
    uses: ./.github/workflows/build-ui.yml

  one:
    name: VoxelDash One
    uses: ./.github/workflows/build-one.yml

  docker:
    name: Docker
    uses: ./.github/workflows/build-docker.yml
    with:
      push: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      channel: dev
    secrets: inherit
